# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='favoritemessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteMessage',
        ),
    ]
